apiVersion: v1
kind: ConfigMap
metadata:
  name: talkgpt-monitoring-config
  namespace: talkgpt
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'talkgpt-mcp'
      static_configs:
      - targets: ['talkgpt-mcp-service:8000']
      metrics_path: /metrics
    - job_name: 'talkgpt-workers'
      static_configs:
      - targets: ['talkgpt-worker-cpu:9090', 'talkgpt-worker-gpu:9090']
      metrics_path: /metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talkgpt-prometheus
  namespace: talkgpt
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: prometheus-config
        configMap:
          name: talkgpt-monitoring-config
---
apiVersion: v1
kind: Service
metadata:
  name: talkgpt-prometheus
  namespace: talkgpt
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: talkgpt-servicemonitor
  namespace: talkgpt
  labels:
    app: talkgpt
spec:
  selector:
    matchLabels:
      app: talkgpt-mcp
  endpoints:
  - port: http
    path: /metrics